# Build

encoding: utf-8
highlighter: pygments
markdown: kramdown
permalink: pretty

# Collections

collections:
  aether:
    output: true
  chiron:
    output: true
  hekate:
    output: true
    
defaults:
  - scope:
      path: ""
    values:
      layout: default
