# Build

encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# permalink: pretty

# Collections

collections:
  aether:
    output: true
  anat:
    output: true
  chiron:
    output: true
  freya:
    output: true
  hekate:
    output: true
  hephaestus:
    output: true
    
defaults:
  - scope:
      path: ""
    values:
      layout: default

# External

twitter:
  name: xyncro/tech
  handle: "@xyncro_tech"
  url: https://twitter.com/xyncro_tech
