# Build

markdown: kramdown

# Collections

collections:
  aether:
    output: true
  chiron:
    output: true
  hekate:
    output: true
    
defaults:
  - scope:
      path: ""
    values:
      layout: default
